site_name: Mkdocs Test
#copyright: "&copy; 2022 mebiusbox"
#repo_url: https://github.com/mebiusbox/MkDocsTest
#repo_name: mebiusbox/MkDocsTest
theme:
  name: material
  font:
    text: Noto Sans JP
    code: Inconsolata
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github
    # repo: fontawesome/brands/gitlab
  custom_dir: overrides
  palette:
    - scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 初期画面: index.md
  - introduction.md
  - material.md
  - section1:
      section1-1:
        section1-1-1:
          sample_page.md
      section1-2:
        section1-2-1:
          sample_page.md
  - extentions.md

plugins:
  search:
    lang: 'ja'

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /
      lang: ja